"""add is_pinned flag

Revision ID: 899eac3559da
Revises: 13256d16e561
Create Date: 2025-11-26 15:33:23.023906

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "899eac3559da"
down_revision: Union[str, Sequence[str], None] = "13256d16e561"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column("is_pinned", sa.Boolean(), nullable=True),
        schema="pam",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "is_pinned", schema="pam")
    # ### end Alembic commands ###
