"""add workflow runners

Revision ID: fa0d7fc468ec
Revises: 899eac3559da
Create Date: 2025-11-26 21:25:25.741350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa0d7fc468ec'
down_revision: Union[str, Sequence[str], None] = '899eac3559da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['pam.users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['pam.workflows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pam'
    )
    op.create_table('workflow_schedules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('repeat_every', sa.String(), nullable=False),
    sa.Column('week_day', sa.Integer(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('meridiem', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['pam.workflows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pam'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_schedules', schema='pam')
    op.drop_table('workflow_runs', schema='pam')
    # ### end Alembic commands ###
