"""add run_options to workflow

Revision ID: 13256d16e561
Revises: 4e6beafe5d72
Create Date: 2025-11-26 14:14:12.642417

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "13256d16e561"
down_revision: Union[str, Sequence[str], None] = "4e6beafe5d72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "workflows",
        sa.Column(
            "run_options", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        schema="pam",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflows", "run_options", schema="pam")
    # ### end Alembic commands ###
